### ISSUE TITLE
Why only stdin

### ISSUE THREAD

**Issue by bluedogtwo** [wezm/titlecase#25]
Why not from argument.
titlecase 'Being productive on linux'

**Comment by wezm** [comment]
> Why not from argument.

stdin was the use case I had when I built the tool originally: to select text in vim and filter it through `titlecase` and no one has requested otherwise.

**Comment by alerque** [comment]
@bluedogtwo You can use my `decasify` create as a CLI four that usage. It handles either STDIN or arguments. The default English title casing is powerd by this crate so you should get the same output (with options for other languages, style guides, and other cases too).

**Comment by bluedogtwo** [comment]
@alerque aha, didn't know about that, thanks.

**Comment by wezm** [comment]
That's quite neat. My requirements are pretty basic though, I just like to format headings and titles of blog posts so I just do `V:!titlecase`  as needed.

**Comment by alerque** [comment]
Fair enough. And thanks again for *this* crate; as quite useful as a library to cover at least Daring Firefall's approach to English title casing.
