### ISSUE TITLE
Pre-compiled binaries for Linux not accessible

### ISSUE THREAD

**Issue by kwbr** [wezm/titlecase#28]
Trying to download `https://releases.wezm.net/titlecase/3.3.0/titlecase-3.3.0-x86_64-unknown-linux-musl.tar.gz` results in the following error:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>8SXA7M0MFB2JFV8M</RequestId>
<HostId>
9AzePdokr5o38ofk9xKwA/6mZMHAXEGxQRJuO6nHT26C+8zvrjc6/J/YFahMVHQJueTgMSeZIG8=
</HostId>
</Error>
```

**Comment by wezm** [comment]
Oops. Looks like I typoed the links in the release. Should be `v3.3.0` and not just `3.3.0`:

https://releases.wezm.net/titlecase/v3.3.0/titlecase-v3.3.0-x86_64-unknown-linux-musl.tar.gz

I've updated the links on the release as well.
