### ISSUE TITLE
Mac OS pre-compiled binary exec format error

### ISSUE THREAD

**Issue by mrfragger** [wezm/titlecase#29]
Mac OS 14.5 Sonoma
downloaded pre-compiled binary

sudo mv titlecase /usr/local/bin

I use the brew install titlecase (perl version) and also used pip3 install titlecase (python) one no problems.
The reason I'm interested in this rust version is perhaps I windows it might be the easiest to install of the three.

echo "088 He's a Very Naughty Boy: the Infancy Stuff of Thomas" | titlecase
zsh: exec format error: titlecase

**Comment by wezm** [comment]
Strange. The has the roughly right structure:

```
$ file titlecase
titlecase: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
titlecase (for architecture x86_64):	Mach-O 64-bit executable x86_64
titlecase (for architecture arm64):	Mach-O 64-bit executable arm64
```

And I can run it on my old Intel MacBook, I assume you've can an ARM based Mac? I'll have to get some time on my wife's ARM Mac to try it there.

**Comment by wezm** [comment]
Also what does `file /usr/local/bin/titlecase` show for you?

**Comment by mrfragger** [comment]
file /usr/local/bin/titlecase
/usr/local/bin/titlecase: MacOS Alias file
yea I have a Mac M1

**Comment by wezm** [comment]
> file /usr/local/bin/titlecase
> /usr/local/bin/titlecase: MacOS Alias file

Hmm that doesn't seem consistent with:

```
 downloaded pre-compiled binary

sudo mv titlecase /usr/local/bin
```

Are you able to try:

```
cd ~/Downloads
curl -OL https://releases.wezm.net/titlecase/v3.3.0/titlecase-v3.3.0-universal-apple-darwin.tar.gz
tar zxf titlecase-v3.3.0-universal-apple-darwin.tar.gz
file titlecase
echo test | ./titlecase
```

**Comment by alerque** [comment]
The output of `file` showing an alias instead of your binary doesn't make sense at all. Did you perhaps have a prior symlink to a directory in that location and your move ended up moving it into the symlinked directory instead?

----

Also as a side note [decasify](https://github.com/alerque/decasify) which uses this crate under the hood for English title casing is available on Homebrew:

```console
$ brew install decasify
...
$echo test | decasify
Test
```

The difference is the binary is going to be a bit bigger because it comes with support for other languages, cases, and style guides besides this one as well.

**Comment by mrfragger** [comment]
yea I'm been aware of decasify for a couple weeks which also has support for Turkish. Will consider using it on Windows perhaps. Maybe it was a left over symlink from the python titlecase...not sure.

**Comment by mrfragger** [comment]
`"088 He's a Very Naughty Boy： the Infancy stuff of Thomas"; newtitle=$(echo "$title" | sed -E -e 's/^([0-9]+)//g' -e 's/：/:/g' -e 's/\|/-/g' -e 's/\//-/g'); num=$(echo "$title" | sed -E 's/(^[0-9]+ )*(.*)/\1/g'); echo -n "$num"; echo -n "$newtitle" | awk 'BEGIN{split("a the to at in of on with and but or",w); for(i in w)nocap[w[i]]}function cap(word){return toupper(substr(word,1,1)) tolower(substr(word,2))}{for(i=1;i<=NF;++i){printf "%s%s",(i==1||i==NF||!(tolower($i) in nocap)?cap($i):tolower($i)),(i==NF?"\n":" ")}}' | gsed -E -e 's/(\s*-\s*)([a-z])/\1\u\2/g' -e 's/(\s*:\s*)([a-z])/\1\u\2/g' -e 's/(^[0-9]+) ([a-z])/\1 \u\2/g'`

btw this awk script works decent but obviously can't do acronyms like titlecase or decasify or a few other exceptions.  One thing though I had to add was e 's/：/:/g' .....not sure where this ：comes from maybe Arabic I'm guessing.  So possibly consider making rules apply to that unicode character too as already : is taken into account.
